### ISSUE TITLE
Centering with flex

### ISSUE THREAD

**Issue by andrzey** [chenjiahan/rodal#18]
Im struggling to center the modal with flex. Do you have an example on how to do that?

**Comment by chenjiahan** [comment]
Please upgrade to v1.4.0 and try this:

js
``` javascript
<Rodal 
    visible={this.state.visible} 
    onClose={this.hide.bind(this)}
    className="rodal-flex"
>
    <div>Content</div>
</Rodal>
```

css
``` css
.rodal-flex {
    display: flex;
    align-items: center;
    justify-content: center;
}

.rodal-flex .rodal-dialog {
    top: auto;
    left: auto;
    right: auto;
    bottom: auto;
}
```
